### ISSUE TITLE
Beta Testers Needed - Version 1.1.0

### ISSUE THREAD

**Issue by donavanbecker** [donavanbecker/homebridge-honeywell-home-roomsensors#18]
A change to Honeywell API has Happened, refresh tokens are expiring sooner then before so implemented a change to see if this will fix the issue if you you are getting a new refresh token on restarts.

To Test:
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```
To Revert:
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@latest
```

**Comment by trevor-gililland** [comment]
What I have noticed now with both betas installed is it fails with the error: "Cannot add a bridged Accessory with the same UUID as another bridged Accessory"

**Comment by trevor-gililland** [comment]
With the room sensors beta uninstalled and just the home beta installed, I am now seeing the same error as before: "Could not discover devices. Request failed with status code 400"

**Comment by donavanbecker** [comment]
Can you send me that log? Also models of the thermostats? 

Also if possible can you clear cache on the two plugins? And see if you have the issue?

**Comment by donavanbecker** [comment]
> With the room sensors beta uninstalled and just the home beta installed, I am now seeing the same error as before: "Could not discover devices. Request failed with status code 400"
> 
> 

You may have to relink your Honeywell account with config ui.

**Comment by trevor-gililland** [comment]
After a complete refresh of all plugins and relinking, they are both working fine! Thanks for the assist.

**Comment by donavanbecker** [comment]
@trevor-gililland release a new beta update if you would test this new one thanks!

**Comment by trevor-gililland** [comment]
Both new betas seem to be working just fine. On a side note, I am trying to work with automation on my end to enable a system shutoff once the thermostat reaches the desired temp range while in Auto mode. Can you help me expose a on/off switch for when the temp range is hit? Maybe some sort of auto on/off state? If this is too much to ask, I completely understand as my use case may not be common at all.

**Comment by donavanbecker** [comment]
@trevor-gililland I totally understand where you are coming from with wanting to run automations. I would prefer if we left this plugin as is. I want the plugin to be as closes to as it would be if it had official HomeKit support.

**Comment by trevor-gililland** [comment]
I completely understand. Was worth an ask! Thanks again for all your hard work on these builds, looks like I need to fork off yours to accomplish my task. As for these betas, I have continued on testing while watching logs and things still look good. I will update if I see any anomalies in the future.

**Comment by trevor-gililland** [comment]
Well now after running for about 10 min, I am seeing this error (last line):

[7/30/2020, 11:20:31 AM] [HoneywellHome] Got access token: VGZYIgXXXXXXX
[7/30/2020, 11:20:31 AM] [HoneywellHome] New refresh token: P93vi6Y9XXXXXX
[7/30/2020, 11:20:31 AM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[7/30/2020, 11:20:31 AM] [HoneywellHome] Got access token: wCpfEtjn5bzXXXXXXX
[7/30/2020, 11:20:31 AM] [HoneywellHome] New refresh token: dhw2VPAgn35AGyXXXXXXX
[7/30/2020, 11:20:31 AM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[7/30/2020, 11:20:31 AM] [HoneywellHome] Failed to update status of Living Room Request failed with status code 401

**Comment by donavanbecker** [comment]
> Well now after running for about 10 min, I am seeing this error (last line):
>
> [7/30/2020, 11:20:31 AM] [HoneywellHome] Failed to update status of Living Room Request failed with status code 401

Yeah I have seen this error too but seems like the thermostat still reacts to homekit. so not sure how we would fix this.....
